### ISSUE TITLE
Continuous integration to run tests on pull requests

### ISSUE THREAD

**Issue by wetneb** [tdf/odftoolkit#133]
This repository does not seem to have Continuous Integration set up.
As a contributor, when I open a pull request to a Java library, I expect that tests will be run automatically on it and that the maintainer will be able to merge this pull request based on those results and their review.

It would be easy to add this using GitHub Actions.

**Comment by svanteschubert** [comment]
Hej thanks! 👍 
Incidentally, I started reading myself into GitHub Actions over the weekend... :-)

Currently, we have Travis as CI. 
Builds should be triggered after a commit:
https://github.com/tdf/odftoolkit/blob/master/.travis.yml
and usually, we receive automatically a green/red build for every pull request from GitHub, too.

Nevertheless, I would love to have downloadable artefacts as well as GitHub Releases (and not only as Maven repository deployment).
The above perhaps triggered by adding an action listening to certain Git tag event:
https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onpushpull_requestbranchestags

I am reading a bit further into it and to some testing with your PR and will come back to you!

**Comment by svanteschubert** [comment]
PS: I would try to reuse some existing working YAML from projects that I am following:
https://github.com/ShiftLeftSecurity/codepropertygraph/tree/master/.github/workflows
or perhaps from a pure Java project ;-)

YAML being a superset of JSON was easy to learn: https://learnxinyminutes.com/docs/yaml/

**Comment by mistmist** [comment]
we did set up Travis CI some years ago, i think i saw it working just recently?

https://app.travis-ci.com/github/tdf/odftoolkit/builds

says latest build is 3 months ago... was this PR: https://github.com/tdf/odftoolkit/pull/122

the later ones don't have any comments from Travis, which i didn't notice at the time :)

in the project settings, Apps & Integrations still shows Travis CI but it's not clickable.

**Comment by wetneb** [comment]
Travis is basically shutting down and has no longer the capacity to support OSS projects, sadly: https://www.r-bloggers.com/2020/11/moving-away-from-travis-ci/
