### ISSUE TITLE
Avoiding Whitespace Noise from Commits by Automation/GitHooks

### ISSUE THREAD

**Issue by svanteschubert** [tdf/odftoolkit#15]
The changes of whitespaces (trailing spaces, tabs vs. spaces) are handled by many code editing application different and cause unintended noise for reviewers of commits.
Even I got problems myself when using multiple editors such as Netbeans, JEdit, UltraEdit and VSCode.

I suggest to add some automated Maven/GitHook tooling to our system, which normalizes all whitespaces. In other words, to avoid noise for reviewers every commit of an author is being space-normalized before it reaches GitHub.

It would be very desireable to have this tooling before we do our next release to keep the delta to follow up releases as low as possible.

**Comment by hpham** [comment]
Hi Svante,

perhaps  https://editorconfig.org/ can helps. Here are some editor support .editorconfig: 

https://editorconfig.org/#download

Regards 
Hanh

**Comment by svanteschubert** [comment]
That is very interesting, GitHub has native support for editconfig, it runs out-of-the-box in various editors (like IntelliJ) and with Plugin for editors such VisualStudioCode, Eclipse, Sublime, etc.
And there is even a Maven Plugin - https://ec4j.github.io/editorconfig-maven-plugin/

Would you like to come up with an exampe for it for our project? Even a patch perhaps?
I am still stuck with updating the documentation.. 

Cheers,
Svante

**Comment by svanteschubert** [comment]
I was curious and I have started a branch issue-15 with a new config file ".editorconfig" and a new Maven plugin in a new branch: https://github.com/tdf/odftoolkit/compare/issue-15
So far I only added the changed pom.xml itself so we can now discuss on the configuration instead being polluted by noise of changed spaces ;-)

For configuration details see: 
https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties

You simply run from command line:
mvn editorconfig:format
Within the ODFDOM project I would roll it out for all projects, but let's start simple.

I used the following Maven plugin: https://ec4j.github.io/editorconfig-maven-plugin/
Also I do not apply it to all files, but only I have included a handful, see odfdom/pom.xml 
<includes>
    <include>pom.xml</include>
    <include>src/codegen/resources/config.xml</include>
    <include>src/codegen/resources/pkg/config.xml</include>
    <include>src/codegen/resources/pkg/javacodetemplate.xml</include>
    <include>src/main/java/org/odftoolkit/odfdom/doc/OdfChartDocument.java</include>						

Does this configuration suit you? Later for all Java and XML files and all projects?
Any Pro/Cons on the configuration?

PS: Somehow I have hoped that the branch would automaticalle align with this issue, any idea what I have missed?

**Comment by svanteschubert** [comment]
As the tavis test failed (likely due to the build in support of .editorconfig of GitHub) I have changed my mind and transformed all files (see subset in config) of the ODFDOM project.
If you like the configuration I would add the same configuration for all other ODF Toolkit projects.

NOTE: For review, fokus on the odfdom/pom.xml and odfdom/.editorconfig file, otherwise it is a review of whitespace adoption ;-)

**Comment by hpham** [comment]
Hi 
.editorconfig looks fine. But do you really want indent_style as tab? I think in Java project the indent_style is space.

Regards
Hanh

**Comment by svanteschubert** [comment]
Hi,

I was using once TAB for XSLT files to lower the size, but you are right,
let's switch in general to SPACE!

PS: Documentation takes longer than expected, hopefully I push some new
updates next week ..

Have a nice week-end,
Svante

Am Sa., 8. Juni 2019 um 13:23 Uhr schrieb hpham <notifications@github.com>:

**Comment by hpham** [comment]
That is fine.

**Comment by svanteschubert** [comment]
I have added a new pull request for review:
https://github.com/tdf/odftoolkit/pull/18

**Comment by svanteschubert** [comment]
Merged the according pull request: https://github.com/tdf/odftoolkit/pull/18
