### ISSUE TITLE
Compile / Test Error in MavenCleanup Branch

### ISSUE THREAD

**Issue by 0x000eHx** [tdf/odftoolkit#17]
Hey guys and girls,
I want to use the ODF Toolkit to work with a table (.ods file), but I don't manage to compile the project properly.
On the introduction page is written to use maven. So I downloaded it, set the enviroment path under my win 7 installation and checked for the right java sdk (its the latest java 8 - 1.8_212) set as JAVA_HOME as enviroment path. (As the [Maven website describes](http://maven.apache.org/install.html))
I cloned the MavenCleanup Branch with this command:
`git clone https://github.com/tdf/odftoolkit.git -b MavenCleanup --single-branch`
into the working directory and tried
`mvn clean install` in it.

These Errors get shown at the end of the terminal output:
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running schema2template.example.ExampleGenerationTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 88.269 sec - in schema2template.example.ExampleGenerationTest
Running schema2template.example.odf.OdfTemplateAPICoverageTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in schema2template.example.odf.OdfTemplateAPICoverageTest
Running schema2template.example.odf.PuzzlePieceTest
Tests run: 3, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 0.031 sec <<< FAILURE! - in schema2template.example.odf.PuzzlePieceTest
testMSVExpressionTree(schema2template.example.odf.PuzzlePieceTest)  Time elapsed: 0.031 sec  <<< FAILURE!
java.lang.AssertionError: 
There is a difference between the expected outcome of the parsed ODF 1.0 tree.
Please compare the output:
	'target\odf10-msvtree.dump'
with the reference
	'target\classes\examples\odf\odf-schemas\OpenDocument-strict-schema-v1.0-os.rng
	at schema2template.example.odf.PuzzlePieceTest.testMSVExpressionTree(PuzzlePieceTest.java:90)

Running schema2template.TemplateAPICoverageTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in schema2template.TemplateAPICoverageTest

Results :

Failed tests: 
  PuzzlePieceTest.testMSVExpressionTree:90 There is a difference between the expected outcome of the parsed ODF 1.0 tree.
Please compare the output:
	'target\odf10-msvtree.dump'
with the reference
	'target\classes\examples\odf\odf-schemas\OpenDocument-strict-schema-v1.0-os.rng

Tests run: 6, Failures: 1, Errors: 0, Skipped: 2

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for The ODF Toolkit 0.9.0-SNAPSHOT:
[INFO] 
[INFO] The ODF Toolkit .................................... SUCCESS [  2.793 s]
[INFO] ODF Custom Javadoc Taglets ......................... SUCCESS [  6.218 s]
[INFO] XML Schema to Template Mapping Tool: Parent POM .... SUCCESS [  0.078 s]
[INFO] XML Schema to Template Mapping Tool: Library ....... FAILURE [01:34 min]
[INFO] XML Schema to Template Mapping Tool: Maven2 Plugin . SKIPPED
[INFO] ODFDOM ............................................. SKIPPED
[INFO] ODF XSLT-Runner .................................... SKIPPED
[INFO] ODF XSLT-Runner Ant Task ........................... SKIPPED
[INFO] ODF Validator ...................................... SKIPPED
[INFO] Simple Java API for ODF (Simple ODF) ............... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:44 min
[INFO] Finished at: 2019-05-27T15:02:27+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project schema2template: There are test failures.
```

It seems that the maven-surefire-plugin test doesn't work, so the complete project won't compile.
Is there another solution than skipping tests completely with
`mvn install -DskipTests`
or disabling something in the pom.xml ?
```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>2.19.1</version>
    <configuration>
        <testFailureIgnore>true</testFailureIgnore>
    </configuration>
</plugin>
```
(btw, that last tip from stackoverflow didn't work out)

Can somebody help me getting this compiled without errors?

Thanks in advance! :)

**Comment by svanteschubert** [comment]
Hi,

this test is about source code generation and is not of importance for
using it at run-time.
Unfortunately this tests fails from time to time, it seemed stable with
recent JDK versions, but there might be a race condition in the
MultiSchemaValiator.
You might disable it by @ignore above the Java Test
schema2template.example.odf.PuzzlePieceTest above the method
testMSVExpressionTree()

Good luck ;-)
Svante



Am Mo., 27. Mai 2019 um 16:35 Uhr schrieb 0x000eHx <notifications@github.com

**Comment by 0x000eHx** [comment]
Do you recommend your newer branch for Java 11+ ? Is the odf toolkit working stable with the current Java Framework?

**Comment by svanteschubert** [comment]
You may use what you like, the Java 11+ branch was basically the backend of
some weboffice in production so we can consider it stable.
But if you are using JDK 8 you might as well stick with the current branch.
As you prefer it :-)

Cheers,
Svante

Am Di., 28. Mai 2019 um 11:05 Uhr schrieb 0x000eHx <notifications@github.com
