### ISSUE TITLE
Cloning fails on Windows

### ISSUE THREAD

**Issue by Asbjoedt** [tdf/odftoolkit#218]
Hi

I try to clone the project into Idea on Windows, but the cloning fails because four filenames are too long. I then try to clone on Linux and it succeeds without problems. I know Windows has a character limit on filenames.

Is it possible to get these four filenames shortened for Windows support?

**Error log**
```
Clone failed

Filename too long unable to create file generator/schema2template/src/test/resources/test-reference/odf/graphml/odf-schema-1.0/_text_page-count_text_paragraph-count_text_word-count_text_character-count_text_table-count_text_image-count_text_object-count.graphml

Filename too long unable to create file generator/schema2template/src/test/resources/test-reference/odf/graphml/odf-schema-1.1/_text_page-count_text_paragraph-count_text_word-count_text_character-count_text_table-count_text_image-count_text_object-count.graphml

Filename too long unable to create file generator/schema2template/src/test/resources/test-reference/odf/graphml/odf-schema-1.2/_text_page-count_text_paragraph-count_text_word-count_text_character-count_text_table-count_text_image-count_text_object-count.graphml

Filename too long unable to create file generator/schema2template/src/test/resources/test-reference/odf/graphml/odf-schema-1.3/_text_page-count_text_paragraph-count_text_word-count_text_character-count_text_table-count_text_image-count_text_object-count.graphml

Filename too long unable to checkout working tree warning
```

**Comment by mistmist** [comment]
that's a surprising problem... only Svante (who is traveling currently) knows if these can be renamed but the "test-reference" indicates that it's something generated and to be compared with future results of the code generation...

i tried it with git-for-windows and apparently it depends on the total length of the path:
"git clone" inside "/c/cygwin/home/ms/lo" is successful
"git clone" inside "/c/cygwin/home/ms/lo/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" fails with this error

is it possible to configure Idea to store it in a shorter path?

**Comment by dennisroczek** [comment]
> that's a surprising problem... 
No, that's a known problem on Windows with filenames and folders (in combination) should not be longer than 255 characters... and this although NTFS is able to handle even more characters... 🙈

> is it possible to configure Idea to store it in a shorter path?
`subst G: c:\my\path\to\git\odftoolkit\`
might help to shorten the links to a minimum in my experience. (so creating another (virtual) partition linking to the git folder)

Well, this subst'ing commands needs to be typed every startup as windows forgets such stuff sadly.
