### ISSUE TITLE
Small mistake in odftoolkit v0.9RC description?

### ISSUE THREAD

**Issue by 0x000eHx** [tdf/odftoolkit#23]
Hey there,
in your release of the odftoolkit v0.9 RC, where you wanted to skip the SimpleAPI part I found something strange. If I use the odfdom namespace with this verison, it markes an object of the OdfTable class in _org.odftoolkit.odfdom.doc.table_ as **deprecated** with this explanation:
> org.odftoolkit.odfdom.doc.table
> Class OdfTable
>     Deprecated. 
>     As of release 0.8.8, replaced by org.odftoolkit.simple.table.Table in Simple API.

( found here: [https://odftoolkit.org/api/odfdom/org/odftoolkit/odfdom/doc/table/OdfTable.html](https://odftoolkit.org/api/odfdom...) )
My english might not be "the yellow from the egg", but shouldn't it be the other way round?
Like all the stuff out of the SimpleAPI namespace (_org.odftoolkit.simple._..) should be marked deprecated and the odfdom namespace stuff (_org.odftoolkit.odfdom._..) should be still considered current?
I find it a little illogical to declare the odfdom namespace in the old 0.9RC as deprecated and the simpleapi as standard, but in verison 1.0 simpleapi wont exsist anymore...

Greetings and thanks for the clarification :)

**Comment by svanteschubert** [comment]
Thanks for the notification, I have removed the deprecation entirely because we deprecated the Simple API due to duplicated code instead.
A detailed explanation is on the mailing list: 
https://listarchives.odftoolkit.org/dev/msg00023.html

Thanks again,
Svante
