### ISSUE TITLE
Determine font, font size, bold/italic/underline styles

### ISSUE THREAD

**Issue by j-dimension** [tdf/odftoolkit#242]
Hi, 

I am kind of stuck determining the styling of an element. My code looks like this:

```
            if (childNode.getNodeName().equals("text:p")) {
                    OdfElement odfElement = (OdfElement) childNode;
                    TextPElement pElement = (TextPElement) odfElement;
                    Paragraph newP = targetDoc.addParagraph(pElement.getTextContent());
                
            }
```

Basically I am browsing a source document and selectively add its content to a target document. I would like to preserve styling - in the example above, I am copying a paragrahs text, and then want to apply the same styling. 
However, I have no idea how to determine e.g. 

- font
- font size
- bold/italic/underline styles

Could you help pointing in the right direction?

Thanks!

**Comment by svanteschubert** [comment]
Hi Jens,

It was years ago that I used this functionality, so I looked into our regression tests of ODFDOM.
Starting in those, that have something do to with Style:
https://github.com/tdf/odftoolkit/blob/master/odfdom/src/test/java/org/odftoolkit/odfdom/doc/StyleTest.java#L307
Hope that points you in the right direction! 
If you looked in the docu and expected something that was missing, I would be happy if you could fill that gap from what you learned with a PR! :-)

Thanks in adanvce and greetings from Berlin Tegel, Jens, could it be we live just 12km away? ;-)
Svante

**Comment by j-dimension** [comment]
Hi Svante, 

thanks, very helpful indeed! Should've grepped the tests myself, will do so in the future!

I am actually based 2hrs south of Berlin. Let me know when you're in the area and I will take you on a local micro brewery tour :-D
