### ISSUE TITLE
Diskussion Forum

### ISSUE THREAD

**Issue by rsoika** [tdf/odftoolkit#243]
Hi, what do you think about enabling the 'Discussion' option for this repo?

![image](https://github.com/tdf/odftoolkit/assets/1339124/06388a70-6b8e-4a48-a0f1-22ef6b20bbd3)

Discussion have the big advantage that :
- you can convert an issue into a discussion without loosing the current conversation
- users can search and follow discussions even after a long time
- we can better separate questions from open issues

===
Ralph

**Comment by svanteschubert** [comment]
Thanks for pointing this out, Ralph! Yeah, let's give it a try!
