### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by smehrbrodt** [tdf/odftoolkit#29]
On this [page](https://odftoolkit.org/odfdom/index.html) the link "JavaDoc as bundle" leads to https://odftoolkit.org/odfdom/odftoolkit.org/api/odfdom/index.html which results in 404.

**Comment by svanteschubert** [comment]
We should collect all dead links into one issue in the future (as lone one is open), I will take care of them for now. Thx! :-)

**Comment by black-snow** [comment]
The whole documentation section in the README is dead, e.g. https://tdf.github.io/odftoolkit/docs/odfdom/index.html

**Comment by svanteschubert** [comment]
Yes, we realized the old/deprecated Apache CMS is creating HTML with an empty body without an error.
A quick workaround is given by Sebastian MD2HTML java-based generation is provided/tested on a fork of mine:
https://svanteschubert.github.io/tdf-odftoolkit-fork/docs/odfdom/index.html

I am currently working on the generator module enabling all tests to generate an ODF 1.3 DOM, doing three releases in a row with all updated documentation.

**Comment by svanteschubert** [comment]
Aside from the references to the Maven artefacts 0.9.0 and 0.10.0 (which might follow later today, when I am able to tame the generator) all links should be fixed at the 0.10-docu branch viewed at the moment at:
https://svanteschubert.github.io/odftoolkit/

In addition, I have used https://www.drlinkcheck.com/ to check for broken links on the above draft site.
