### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by Junzz0** [tdf/odftoolkit#292]
Please ask if the library will be compatible with Android, or if there is any open source Android ODF library recommendation, thanks.

**Comment by rsoika** [comment]
It would make sense if you describe your problem and show your code and error messages. What do you expect just telling the community that you get an error?

**Comment by svanteschubert** [comment]
@Junzz0 What was your test environment and what was the error?

[Different versions of Android support different versions of Java](https://stackoverflow.com/questions/54129834/which-android-versions-run-which-java-versions/76621845#76621845)
and
[**ODF Toolkit >= version 0.10.0** is using **Java version >= 9**](https://odftoolkit.org/source.html).

Aside from the Android/Java support, I see no general problem using the ODF Toolkit on Android.
