### ISSUE TITLE
Add regression tests for MarkDown to HTML creation

### ISSUE THREAD

**Issue by smehrbrodt** [tdf/odftoolkit#30]
On this [page](https://odftoolkit.org/xsltrunner/ODFXSLTRunner.html) the link "driver" leads to http://incubator.apache.org/odftoolkit/xsltrunner/ODFXSLTRunnerTask.html which results in 404.

**Comment by svanteschubert** [comment]
I noticed this myself, we need to add some regression test, that no empty content is being created with the Apache CMS system.

**Comment by svanteschubert** [comment]
The reason for the missing body was a problem of the old Apache CMS and markdown2html converter with text-indent.
Removing those make those pages reappear. But we need to move to a modern site documentation system anyway, I will write a follow-up issue afterwards, but here as teaser/spoiler: Sphinx! :-)
