### ISSUE TITLE
Error when using "-g" option

### ISSUE THREAD

**Issue by s8321414** [tdf/odftoolkit#319]
If we use latest odfvalidator to check some files with `-g` option, it will show error message like this:
`file:///path/to/odffile/META-INF/manifest.xml: Error: Invalid root element: manifest:manifest`
Every document will get this result even if using vanilla LibreOffice to create a file that contains only "test" or some other word.

**Comment by svanteschubert** [comment]
Please add a test to let us reproduce the scenario or a test file attached to this issue of those mistakes, might already solve the riddle. If you want to solve it yourself, just debug the validator and send a patch, please! :-)

Just checked the source (via grep), and this error might be triggered at two locations in the validator:

1. https://github.com/tdf/odftoolkit/blob/master/validator/src/main/java/org/odftoolkit/odfvalidator/MetaFilter.java#L81
2. https://github.com/tdf/odftoolkit/blob/master/validator/src/main/java/org/odftoolkit/odfvalidator/ContentFilter.java#L109

(And yes, the error messages should be named slightly differently here, so we have no ambiguity.)
Obviously, the root element (or what element is taken as root) does not have the correct namespace or local name... but perhaps the wrong element is provided?
Test will tell ;-)

**Comment by svanteschubert** [comment]
Oh, I have overread the "-g" option part, so you might want to debug the following three lines:
https://github.com/tdf/odftoolkit/blob/master/validator/src/main/java/org/odftoolkit/odfvalidator/Main.java#L163
