### ISSUE TITLE
Localisation Based NumberFormatException on getWidth

### ISSUE THREAD

**Issue by AndreasTAK** [tdf/odftoolkit#332]
Depending on Locale OdfTableColumn.getWidth() produces a NumberFormatException.
Steps to reproduce

1. Set computer locale to "de" (german)
2. run the following code 
```
     var spreadsheetDocument = OdfSpreadsheetDocument.newSpreadsheetDocument();
     var table = OdfTable.newTable(spreadsheetDocument);
     var columnWidth = table.getColumnByIndex(0).getWidth();
```
will lead to:

```
java.lang.NumberFormatException: For input string: "001,2000"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:792)
	at java.base/java.lang.Double.valueOf(Double.java:755)
	at org.odftoolkit.odfdom.type.Length.parseDouble(Length.java:207)
	at org.odftoolkit.odfdom.type.Length.parseLong(Length.java:179)
	at org.odftoolkit.odfdom.doc.table.OdfTableColumn.getWidth(OdfTableColumn.java:144)
	at org.odftoolkit.odfdom.doc.table.OdfTableColumn.setWidth(OdfTableColumn.java:173)
```

**Comment by svanteschubert** [comment]
Any chance of getting a patch from you, Andreas? It would be most welcome! 🤗

**Comment by AndreasTAK** [comment]
@svanteschubert so I looked into it and the issue originally stems from the [createTable()](https://github.com/tdf/odftoolkit/blob/804c946c04efe96020c55fe14166cbd3c1f6fd7f/odfdom/src/main/java/org/odftoolkit/odfdom/doc/table/OdfTable.java#L346) method. To define the `column-width` style attribute `java.text.DecimalFormat` is used without a `DecimalFormatSymbols` parameter which then defaults to the users OS locale. I am not sure if the potentially resulting string using `,` as a decimal separator conforms with OpenDocument specs. LibreOffice handles it fine, Microsoft Excel does not. My proposed fix would be to define the `DecimalFormatSymbols` with the English Locale. You use `DecimalFormat` without a defined `DecimalFormatSymbols` in `OdfTableCell.java` as well however I did not look into whether this could lead to the same issue yet. I have implemented the fix in #333

**Comment by AndreasTAK** [comment]
@svanteschubert I have added a test to demostrate my fix works with german locale.    
Also I checked into the other two instances where DecimalFormat is used. 
Both these instances only affect DisplayText which is never parsed as an actual number so no Exception occurs, in this case using the default System locale is most likely fine and I think doesn't need changing. 
As is noted by the documentation of the `setDisplayText` method in `OdfTableCell` and I just also confirmed with my own testing both for microsoft excel as for LibreOffice most odf viewers calculate the display value for table cells themselves and disregard what is in the display text property. 
In case a change is desired anyway since this is in regards to the display text I am not sure if the system default, the documents locale or simply a unified english locale would be the best choice. 

Greetings from Vienna, Austria👋

**Comment by svanteschubert** [comment]
@AndreasTAK @mistmist 
Thank you both, I have just uploaded another SNAPSHOT release for all ODF Toolkit deliverables, like for the validator at
https://oss.sonatype.org/content/repositories/snapshots/org/odftoolkit/odfvalidator/0.13.0-SNAPSHOT/

**Comment by AndreasTAK** [comment]
@svanteschubert Fantastic. Thanks for the quick review and SNAPSHOT release. I'll keep my eyes open for any other issues I might find
