### ISSUE TITLE
Working with tables: Split and freeze

### ISSUE THREAD

**Issue by gerrit-hohl** [tdf/odftoolkit#51]
Hello everyone,

I'm currently working with the version 0.9.0-RC1 of the odfdom-java artifact (still bound to Java 1.8, so I can't use the  1.0.0-BETA1).

In OpenOffice you'll find "Split" and "Freeze" in the "Window" menu.

I went up and down the API (`OdfTable`, `OdfTableColumn`, `OdfTableRow`, `OdfTableCell`), but couldn't find any method related to that. I also created a speadsheet in OpenOffice, loaded it via the ODF Toolkit and analysed all the styles, but also couldn't find any information or clue there.

Is this a bug? A missing feature? Not in the standard of the ODS format, but in some unstandardised fields only OpenOffice knows? 🤔 Or is the problem in the front of screen? 😏

**Comment by svanteschubert** [comment]
Hello Gerrit,

I was not sure myself, therefore I tested it.

Let's start making sure we talk about the same things:

   1. The *document format ODF*, which contains the to bytes "shock-frozen"
   information of your run-time ODF application.
   2. A *run-time ODF application with WYSIWG editor*. ODF has its origin
   with StarOffice, where *OpenOffice *was the open-source branch. *LibreOffice
   *forked before Oracle donated the OpenOffice sources to Apache. After
   IBM left the Apache OpenOffice developers it is kind of quiet there AFAIK.
   3. The ODF Toolkit contains *ODFDOM*, which is an ODF run-time model but
   without WYSIWYG.


Furthermore, there are three kind ODF features:

   1. Those being part of the ODF standard, you may find the latest ODF 1.3
   XML feature described by:

   http://docs.oasis-open.org/office/OpenDocument/v1.3/OpenDocument-v1.3-part3-schema.html

   and

   https://tdf.github.io/odftoolkit/docs/odf1.3/OpenDocument-v1.3-cs01-schema-rng.html
   2. Those being new and currently evaluated by an ODF application,
   already serialized, but not yet defined by OASIS. The ODF app named them as
   "extended" standard. In general, those are already in the issue tracker of
   OASIS, on its way to standardization.
   3. Those being saved in the settings.xml not being part of the standard
   and not (yet ?) on the list.

Let's continue below...

Am Sa., 27. Juni 2020 um 11:42 Uhr schrieb Gerrit Hohl <
notifications@github.com>:

> Hello everyone,
>
> I'm currently working with the version 0.9.0-RC1 of the odfdom-java
> artifact.
>
> In OpenOffice you'll find "Split" and "Freeze" in the "Window" menu.
>
I found a description for your WYSIWYG feature:
https://wiki.openoffice.org/wiki/Documentation/OOoAuthors_User_Manual/Getting_Started/Freezing_rows_and_columns
As I installed today myself a LibreOffice 7.0 Beta to test ODF 1.3, I found
your desired choices in LO7 when selecting, a row and using the context
menu.

I added this feature saved and reopened the document and the feature still
existed in the ODS. Therefore I created a simple ODS and saved the file as
a second file when I enabled the freeze feature (find WithoutFreeze.ods and
WithFreeze.ods attached).
The first *2 rows are being freezed *and are not moving when scrolling down.

I opened and indented the XML using JEdit (archive & XML plugin) and
compared them.
Your feature is in the third ODF feature XML category:
In the settings.xml I found the following change from *0 to 2*:
<config:config-item config:name="VerticalSplitPosition" config:type="int">
*2*</config:config-item>

I went up and down the API (OdfTable, OdfTableColumn, OdfTableRow,
> OdfTableCell), but couldn't find any method related to that. I also
> created a speadsheet in OpenOffice, loaded it via the ODF Toolkit and
> analysed all the styles, but also couldn't find any information or clue
> there.
>
ODFDOM is focusing on features from the OASIS standard.
But you might add your feature on top of the DOM of the settings.xml file.

> Is this a bug? A missing feature? Not in the standard of the ODS format,
> but in some unstandardised fields only OpenOffice knows? 🤔 Or is the
> problem in the front of screen? 😏
>
Unstandardised that only OpenOffice / LibreOffice knows.

Have a nice weekend, Gerrit!
Svante

**Comment by svanteschubert** [comment]
So from my perspective, you have the following three options:

1. Assign this feature to yourself and implement it
2. Find someone who implements this issue for you & assigns this feature request to this someone
3. Close it ;-)

The full implementation would be consisting of:

- Implement it for ODFDOM (via the settings.xml as an intermediate solution)
- Gathering support at the LibreOffice Dev list to change the ODF XML from settings.xml to content.xml & styles.xml
Raise an enhancement request at LO (perhaps there is one already)
- If there is an agreement write a JIRA issue for the OASIS TC
- Finally, change the XML support from settings.xml to content.xml & styles.xml according to the final specification. (At that stage I would be much more interested to assist.)

It is quite some work and I am not overtaking the issue as I am riding against my own windmills ;-)
But if you like to do it, I would assist and guide you...

**Comment by svanteschubert** [comment]
Seems GitHub is not supporting attached ODF files, therefore I had to zip them and add that instead:
[FreezeTestDocuments.zip](https://github.com/tdf/odftoolkit/files/4840914/FreezeTestDocuments.zip)

**Comment by gerrit-hohl** [comment]
Thank you very much, @svanteschubert , for your very long and in-detail reply. 😲
I hope it didn't take too much of your precious time. Especially as this line would have been enough information for me. 😏🙇
> Unstandardised that only OpenOffice / LibreOffice knows.
In that case I simply will close the case as it is bearable for my case not having that feature.

Anyway thanks for your reply.

**Comment by svanteschubert** [comment]
@gerrit-hohl 
Don't worry, I was curious myself and I took the time to explain why and how I did this analysis so we are able to point to this issue, in case a similar question arises and let the questioner do this test. ;-)
