### ISSUE TITLE
OdfTableColumn#setWidth(long) throws NumberFormatException

### ISSUE THREAD

**Issue by gerrit-hohl** [tdf/odftoolkit#52]
Hello everyone,

I'm currently working with the version 0.9.0-RC1 of the odfdom-java artifact and came across the following exception when using the OdfTableColumn#setWidth(long) method (I'm trying to create a fresh spreadsheet):

> Caused by: java.lang.NumberFormatException: For input string: "001,2000"
> 	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
> 	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
> 	at java.lang.Double.parseDouble(Double.java:538)
> 	at java.lang.Double.valueOf(Double.java:502)
> 	at org.odftoolkit.odfdom.type.Length.parseDouble(Length.java:192)
> 	at org.odftoolkit.odfdom.type.Length.parseLong(Length.java:164)
> 	at org.odftoolkit.odfdom.doc.table.OdfTableColumn.getWidth(OdfTableColumn.java:146)
> 	at org.odftoolkit.odfdom.doc.table.OdfTableColumn.setWidth(OdfTableColumn.java:175)

Walking up the stack-trace...
- If I understand itcorrectly the method also updates the relative width.
- Therefore it reads the previously set width (via `OdfTableColumn#getWidth()`), which internally calls the `OdfElement#getOdfAttribute(OdfName)` method (somehow I can't dig deeper because Eclipse says it can't debug those classes below the `OdfElement`). The result is an attribute `column-width="001,2000in"` which is cut down in `001,2000in`.
- The result is parsed via `Length.parseLong(String, Unit)` with `Unit` being `Unit.MILLIMETER`.
- That calls `Length.parseDouble(String, Unit)`. Here the method first removes the unit and tries to parse the value as a `Double` - which fails because it expects a `.` instead of a `,` as a decimal point.

Smells like - no, not teen spirit - the problem is different decimal points in different environments. As my OS is German and in Germany the decimal point is a `,`, I assume that a platform dependent formatter somewhere in the code. (Un)fortunately the `Double#valueOf(String)` method is not platform dependent and expects a `.` as decimal point.

**Comment by svanteschubert** [comment]
I am in the middle of the release of 0.9.0 and 1.0.0 release candidate, so without looking deeper into it, you should be aware that there are about 4 years of development time between 0.9.0 and 1.0.0.
In other words, you should switch to 1.0.0 and test the functionality again (even VSCode RedHat Java plugins now comes with a warning that JDK 11 will be mandatory soon). ;-)
If this still fails, you might want to test if the 0.9.0 Simple API offered a patch and we should overtake that functionality into the latest OFDDOM DOC layer classes.

I aim to provide both releases even this month (June), so the master will be the default in GitHub again and containing the 1.0.0 release. Right afterwards, I will start a 2.0.0_ODF1.3 release branch, which should become the new release at the same time when LibreOffice 7.0 is available: Week 32, Aug 3, 2020 - Aug 9, 2020, see https://wiki.documentfoundation.org/ReleasePlan/7.0#7.0.0_release

**Comment by svanteschubert** [comment]
@gerrit-hohl Nevertheless, thank you for the bug report and sorry for the confusion with the branches and where to find the latest features. This mess should be over soon ;-)

**Comment by gerrit-hohl** [comment]
Means there will be a 0.9.0 (Java 1.8) and 1.0.0 (Java >1.8) release? So two at once?

I'm not sure if it is a problem of the version 0.9.0-RC1 or not, but I'm trying to create a simple table for 2 days now. I've already done it with Apache POI and it took me maybe 30 minutes, but only because I had some issue with the format of date and time values (as I wanted to use the default format of the application so it is region independent). After 2 days with 0.9.0-RC1 and even after using the format documentation and analysing an example file I create with OpenOffice 4.1.7, I'm not able to reproduce that simple table with code.

The width of my columns still sticks to the default width. In addition I also can't repeat the 1st row in the print on each page. The format of the time and dates also doesn't work. And it seems there is no support for date and time (in one value) as there are only method for setting date or time.

In Apache POI the code would look like this:
```java
protected void export(Workbook workbook, OutputStream out, Table table) throws IOException {
	Font headerFont;
	CellStyle headerCellStyle, dateTimeCellStyle, dateCellStyle, normalCellStyle;
	Sheet sheet;
	Row row;
	TableHeaderColumn<?> headerColumn;
	Cell cell;
	Object value;
	Integer width;


	headerFont = workbook.createFont();
	headerFont.setBold(true);
	
	headerCellStyle = workbook.createCellStyle();
	headerCellStyle.setFont(headerFont);
	headerCellStyle.setBorderLeft(BorderStyle.MEDIUM);
	headerCellStyle.setBorderTop(BorderStyle.MEDIUM);
	headerCellStyle.setBorderRight(BorderStyle.MEDIUM);
	headerCellStyle.setBorderBottom(BorderStyle.MEDIUM);
	headerCellStyle.setFillForegroundColor(IndexedColors.GREY_25_PERCENT.getIndex());
	headerCellStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);

	dateTimeCellStyle = workbook.createCellStyle();
	dateTimeCellStyle.setDataFormat(FORMAT_DATE_TIME);
	dateTimeCellStyle.setBorderLeft(BorderStyle.THIN);
	dateTimeCellStyle.setBorderTop(BorderStyle.THIN);
	dateTimeCellStyle.setBorderRight(BorderStyle.THIN);
	dateTimeCellStyle.setBorderBottom(BorderStyle.THIN);
	
	dateCellStyle = workbook.createCellStyle();
	dateCellStyle.setDataFormat(FORMAT_DATE);
	dateCellStyle.setBorderLeft(BorderStyle.THIN);
	dateCellStyle.setBorderTop(BorderStyle.THIN);
	dateCellStyle.setBorderRight(BorderStyle.THIN);
	dateCellStyle.setBorderBottom(BorderStyle.THIN);
	
	normalCellStyle = workbook.createCellStyle();
	normalCellStyle.setBorderLeft(BorderStyle.THIN);
	normalCellStyle.setBorderTop(BorderStyle.THIN);
	normalCellStyle.setBorderRight(BorderStyle.THIN);
	normalCellStyle.setBorderBottom(BorderStyle.THIN);
	
	sheet = workbook.createSheet(table.getName());
	sheet.setRepeatingRows(CellRangeAddress.valueOf("1"));
	sheet.createFreezePane(0, 1);

	// --- Header ---
	row = sheet.createRow(0);
	for (int columnIndex = 0; columnIndex < table.getColumnCount(); columnIndex++) {
		headerColumn = table.getHeaderColumn(columnIndex);
		
		width = headerColumn.getWidth();
		if (width != null)
			sheet.setColumnWidth(columnIndex, width.intValue() * 256);
		
		cell = row.createCell(columnIndex);
		cell.setCellStyle(headerCellStyle);
		cell.setCellValue(headerColumn.getName());
	}
	
	// --- Rows ---
	for (int rowIndex = 0; rowIndex < table.getRowCount(); rowIndex++) {
		row = sheet.createRow(rowIndex + 1);
		for (int columnIndex = 0; columnIndex < table.getColumnCount(); columnIndex++) {
			headerColumn = table.getHeaderColumn(columnIndex);
			value = table.getCellValue(rowIndex, headerColumn);

			cell = row.createCell(columnIndex);
			cell.setCellStyle(normalCellStyle);
			if (value == null)
				cell.setBlank();
			else if (String.class.isAssignableFrom(headerColumn.getType())) {
				cell.setCellValue((String) value);
			} else if (Boolean.class.isAssignableFrom(headerColumn.getType())) {
				cell.setCellValue(((Boolean) value).booleanValue());
			} else if (Number.class.isAssignableFrom(headerColumn.getType())) {
				cell.setCellValue(((Number) value).doubleValue());
			} else if (LocalDateTime.class.isAssignableFrom(headerColumn.getType())) {
				cell.setCellStyle(dateTimeCellStyle);
				cell.setCellValue((LocalDateTime) value);
			} else if (LocalDate.class.isAssignableFrom(headerColumn.getType())) {
				cell.setCellStyle(dateCellStyle);
				cell.setCellValue((LocalDate) value);
			} else {
				cell.setCellValue(value.toString());
			}
		}
	}

	workbook.write(out);
}
```

And the result would look like this:
![Apache POI example](https://user-images.githubusercontent.com/11478898/85953922-20736600-b974-11ea-86a7-c75996ce558f.png)

Okay, the freeze thing doesn't work because of issue #51. But the rest should also work with ODS file, I think.
As I already have CSV, XLS and XLSX export - and almost all of my colleagues at work will be fine with those formats, I will pass on the ODS support. Also it would have been nice to have it as I prefer to work with StarOffice / OpenOffice / LibreOffice.

Maybe I'll come back and try again when you've released that stable version and have a look again.

Thanks anyway for all your efforts. 🙂
Somehow it is very rare for people of open source projects to reply so fast and so often. 👍

**Comment by svanteschubert** [comment]
Very interesting! Now my thanks for the longer interesting explanation of yours.
One idea came to my mind - not yet worth if it is worth to pursue. If we have to establish a new high-level API anyway, we might consider to take over from the POI API.
I am curious about what you are working on. We might want to have a chat next week/month by phone if you like? Having a remote tea break, an active pause we called it! 
Just sent me an email if you like.

PS: Usually the weekend is family time and to prevent burn-out at least one day should be computer-free recuperation day, but shortly before summer vacation I stretch my limits a bit ;-)

**Comment by gerrit-hohl** [comment]
Sorry for the late reply, but I didn't have much time until now. But I read you comment on Sunday.

After going back and forth I also thought that my case is maybe out of scope of the library as it focuses more on a high level of control other documents and their structure, while I was aiming for a simple way of writing a sheet.

While searching I also found the Simple API a few times, but didn't try it as it is already deprecated as far as I know. But we definitely cool to have a high-level API (again).

I sent you also an e-mail. If you're SPAM protection hasn't already "eaten" it, you should have received it by now.
