### ISSUE TITLE
Update to modern Jena

### ISSUE THREAD

**Issue by tfmorris** [tdf/odftoolkit#55]
Since you're getting ready to do a new release, would it be possible to update the Jena dependency?

It's currently 3.9 from 2018, but Apache Jena is up to 3.16 now.

**Comment by svanteschubert** [comment]
Updated as follows. New is the requirement of the API dependency slf4j API, otherwise existing tests would fail:
            <dependency>
                <groupId>org.apache.jena</groupId>
                <artifactId>jena-core</artifactId>
                <version>3.16.0</version>
            </dependency>
            <dependency>
                <groupId>org.apache.jena</groupId>
                <artifactId>jena-core</artifactId>
                <classifier>tests</classifier>
                <version>3.16.0</version>
            </dependency>
            
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-api</artifactId>
                <version>1.7.30</version>
            </dependency>
