### ISSUE TITLE
Undeprecate original API

### ISSUE THREAD

**Issue by tfmorris** [tdf/odftoolkit#56]
As I understand it, the deprecation warnings in 0.9.0-RC1 for the original API should be ignored since the Simple API is going away. 

Would it be possible to remove the deprecation tags so that developers aren't misled into doing a pointless migration to an API that is already dead?

**Comment by mistmist** [comment]
that sounds like an excellent idea; could you send a pull request to do that? otherwise we'll have to wait until Svante is back as i'm not so familiar with ODFDOM.

**Comment by tfmorris** [comment]
I've put up PR #56 to address this.

**Comment by svanteschubert** [comment]
@tfmorris Hej Tom, can we close this issue, or was the task lost in confusion - sorry again for that! :-)

**Comment by tfmorris** [comment]
I think so, based on the discussion in #57, but you or @mistmist would know better than I. I found the whole situation very confusing.

**Comment by svanteschubert** [comment]
Hi Tom, thanks for your update. You are right it is/was confusing, I am currently on a FAQ collecting the bits I like to tell and the history (fork/rejoin of IBM's Simple API) is surely one of the things, that should be mentioned...
