### ISSUE TITLE
ODFDOM should support XML default namespace

### ISSUE THREAD

**Issue by jhudsoncedaron** [tdf/odftoolkit#70]
Generated ODS file; may or may not be in the correct format. Calc opens it just fine.

export.ods: Fatal: A qualified name was required, but 'manifest' was given! java.lang.IllegalArgumentException: A qualified name was required, but 'manifest' was given! at org.odftoolkit.odfdom.pkg.OdfNamespace.splitQName(OdfNamespace.java:142) at org.odftoolkit.odfdom.pkg.OdfNamespace.getPrefixPart(OdfNamespace.java:154) at org.odftoolkit.odfdom.pkg.OdfName.newName(OdfName.java:82) at org.odftoolkit.odfdom.pkg.OdfFileDom.createElementNS(OdfFileDom.java:298) at org.odftoolkit.odfdom.pkg.OdfFileSaxHandler.startElement(OdfFileSaxHandler.java:82) at org.odftoolkit.odfdom.pkg.rdfa.MultiContentHandler.startElement(MultiContentHandler.java:76) at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source) at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source) at org.apache.xerces.impl.XMLNSDocumentScannerImpl$NSContentDispatcher.scanRootElementHook(Unknown Source) at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source) at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source) at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) at org.odftoolkit.odfdom.pkg.OdfFileDom.initialize(OdfFileDom.java:236) at org.odftoolkit.odfdom.pkg.OdfFileDom.initialize(OdfFileDom.java:212) at org.odftoolkit.odfdom.pkg.manifest.OdfManifestDom.initialize(OdfManifestDom.java:73) at org.odftoolkit.odfdom.pkg.OdfFileDom.<init>(OdfFileDom.java:132) at org.odftoolkit.odfdom.pkg.manifest.OdfManifestDom.<init>(OdfManifestDom.java:64) at org.odftoolkit.odfdom.pkg.OdfFileDom.newFileDom(OdfFileDom.java:194) at org.odftoolkit.odfdom.pkg.OdfPackage.parseManifest(OdfPackage.java:1313) at org.odftoolkit.odfdom.pkg.OdfPackage.readZip(OdfPackage.java:549) at org.odftoolkit.odfdom.pkg.OdfPackage.initializeZip(OdfPackage.java:519) at org.odftoolkit.odfdom.pkg.OdfPackage.<init>(OdfPackage.java:328) at org.odftoolkit.odfdom.pkg.OdfPackage.loadPackage(OdfPackage.java:439) at org.odftoolkit.odfvalidator.ODFStreamValidator.getPackage(ODFStreamValidator.java:52) at org.odftoolkit.odfvalidator.ODFRootPackageValidator.getPackage(ODFRootPackageValidator.java:59) at org.odftoolkit.odfvalidator.ODFPackageValidator._validate(ODFPackageValidator.java:99) at org.odftoolkit.odfvalidator.ODFPackageValidator.validate(ODFPackageValidator.java:84) at org.odftoolkit.odfvalidator.ODFValidator.validateStream(ODFValidator.java:211) at org.apache.jsp.jsp.validate_jsp._jspService(validate_jsp.java:232) at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:477) at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385) at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329) at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712) at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:580) at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:516) at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:955) at org.apache.jsp.jsp.index_jsp._jspService(index_jsp.java:128) at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:477) at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385) at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329) at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367) at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639) at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.base/java.lang.Thread.run(Thread.java:834) 

Attached file looks like medical data but it's all junk data from a dev box.
[export.zip](https://github.com/tdf/odftoolkit/files/5367830/export.zip)

**Comment by svanteschubert** [comment]
The application "Cedaron.FormBuilder.Presentation" created this file and the ODF Toolkit seems to be surprised by the [default namespace](https://www.w3.org/TR/xml-names/#defaulting) in the /META-INF/manifest.xml file.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest xmlns="urn:oasis:names:tc:opendocument:xmlns:manifest:1.0" version="1.2">
 <file-entry full-path="/" version="1.2" media-type="application/vnd.oasis.opendocument.spreadsheet"/>
 <file-entry full-path="mimetype" media-type="text/plain"/>
 <file-entry full-path="meta.xml" media-type="text/xml"/>
 <file-entry full-path="content.xml" media-type="text/xml"/>
 <file-entry full-path="styles.xml" media-type="text/xml"/>
</manifest>
```
This was obviously unexpected and strangly this missing feature (bug) has not happened earlier.

**Comment by jhudsoncedaron** [comment]
Incidentally I am the author of this part of "Cedaron.FormBuilder.Presentation".

**Comment by svanteschubert** [comment]
@jhudsoncedaron I started fixing it but your manifest has also attributes without prefix, but the default namespace does not work on attributes.
See [default namespace](https://www.w3.org/TR/xml-names/#defaulting) it states: 
"_The namespace name for an unprefixed attribute name always has no value._"

Therefore, in your /META-INF/manifest.xml file it should be written:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest xmlns="urn:oasis:names:tc:opendocument:xmlns:manifest:1.0" version="1.2">
 <file-entry manifest:full-path="/" version="1.2" manifest:media-type="application/vnd.oasis.opendocument.spreadsheet"/>
 <file-entry manifest:full-path="mimetype" manifest:media-type="text/plain"/>
 <file-entry manifest:full-path="meta.xml" manifest:media-type="text/xml"/>
 <file-entry manifest:full-path="content.xml" manifest:media-type="text/xml"/>
 <file-entry manifest:full-path="styles.xml" manifest:media-type="text/xml"/>
</manifest>

**Comment by jhudsoncedaron** [comment]
And that's why I can't quite depend on whether Calc complains or not.

**Comment by jhudsoncedaron** [comment]
I'm confused. You posted a corrected `manifest.xml` with a `manifest:` namespace reference that isn't declared by any `xmlns:manifest`.

**Comment by svanteschubert** [comment]
Yes, I tried to fix it manually and have not validated it, still did not only want to show the attributes.
Now I added the manifest namespace.
Use the validator to see if it is valid. To open broken files is often part of the usability of an application. Students loved already in the last Century StarOffice (LO ancestor) as it could open DOC files, which Word refuses to open. ;-)

BTW I have added an HTML version of the RNG grammar to the ODF 1.3 deliverables:
https://docs.oasis-open.org/office/OpenDocument/v1.3/csd03/schemas/OpenDocument-v1.3-manifest-schema-rng.html#file-entry-attlist

**Comment by svanteschubert** [comment]
In both two SAX ContentHandler odf DOM it will now be checked in case there is an XML namespace if localName and qualifiedName (qName = prefix+localName) are identical. 
If this is the case a new method is being added to create an OdfName with a localName, instead of a qName. OdfNamespace can now be created without a namespace prefix but will try to take the default prefix given by the ODF Specification as a fall-back.
