### ISSUE TITLE
Make odfdom-java an OSGi bundle

### ISSUE THREAD

**Issue by wglas85** [tdf/odftoolkit#78]
We have prepared an internal OSGi bundle for odfdom-0.8.10 and we would like to use odf-dom-1.0.0 as an OSGi bundle.
We already have a prototype running and encountered, that the crucial point is, that the java-rdfa library last released in 2012 is dependent on jena-2, which incurs a lot of historic dependencies.
I have finished the modernization of the library in the repository https://github.com/iteggmbh/java-rdfa and I'm currently discussing with Sonatype on how to gain control over the deployment to the net.rootdev groupId.
If the library needs a change in the groupId, it might be a feasible solution to change to groupId to org.odftoolkit, so the odftoolkit team might deloy a cleaned up version of java-rdfa.

**Comment by wglas85** [comment]
As you might have mentioned, we were able to sort out the deployment problems for java-rdfa with the help of Sonatype and the original author Damian Steer.
Hence, we are now able to build against the cleaned up release 1.0.0-BETA1 of java-rdfa enabling us to build a decent OSGi bundle for odfdom-java.

**Comment by wglas85** [comment]
Hello Svante,
Thanks a lot for merging our pull request.
Do you have any intention to release an odfdom-1.0.0-BETA2 release?
We would highly appreciate such a release, because other wise we have to perform an intermediate odfdom deploy to our private repositories, which is certainly not our preferred way of proceeding.
Judging from the git commit history it seems to be a good point in time, because 1.0.0-BETA1 dates from October 2019 and there have been no changes in November 2020, which might indicate, that the codebase is for the most part "fit for purpose".
Best Regards, Wolfgang

**Comment by svanteschubert** [comment]
Hello Wolfang,

a release is indeed about time.
I was given another deadline next Wednesday and would take a look into it afterwards. Is this a deal?

Best regards,
Svante

**Comment by wglas85** [comment]
Hello Svante,
A Santa Claus release at the end of next week would be very fine ;-)
I don't know, whether the fixes in issue #77 applied to the 0.9 branch apply to the 1.0 master branch, too.
Vice versa, you might check, whether the java-rdfa-1.0.0-BETA1 upgrade turns out to be beneficial for the 0.9 branch.
We are not engaged in the 0.9 efforts, since we decided to move to the future, aka the forthcoming 1.0 version of odfdom.

Best regards,
Wolfgang
