### ISSUE TITLE
Upgrade libs to prevent security issues - CVE

### ISSUE THREAD

**Issue by byjoaofilipe** [tdf/odftoolkit#84]
It was identified by OWASP dependency-checker tool that exists vulnerabilities in odftoolkit-odftoolkit-0.9.0-RC2.
To prevent this security issues, please, upgrade to the latest version the following libraries (see image below):

![image](https://user-images.githubusercontent.com/78802066/107370605-1b19f480-6adb-11eb-8562-f0ed61c5a55e.png)

**Comment by svanteschubert** [comment]
Interesting! How did you trigger the OWASAP dependency-checker? Is it available as a GitHub bot?

There seems to be within the Simple API release an example ZIP, which is not created automatically and therefore contains an old version of Simple API. 

I will take care of it in the next and final release of the deprecated Simple API. 

Thanks for the report.
Svante

**Comment by svanteschubert** [comment]
I was able to install 6.1.0 of
https://jeremylong.github.io/DependencyCheck/dependency-check-cli/index.html
on Linux and create an HTML report
running on the root directory 'dependency-check.sh -s .'

Nice Tool! Thanks again!

**Comment by byjoaofilipe** [comment]
Hello Svante!
You're welcome! :)

Sorry for the delay.
Normally, when I use a framework/lib, I trigger the OWASP dependency-checker to 
verify the existence of security issues or vulnerabilities and report to the project holder.
I'm anxious for the new release and I hope to use on my maven repository soon! 
Keep the good work!
If you need help, you are free to ask.

Thanks!
João Filipe

**Comment by mistmist** [comment]
assuming this is fixed now
